name: Terraform Apply
on:
  push:
    branches:
      - main
permissions:
  id-token: write
jobs:
  TerraformApply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::808191491911:role/terraform-20240406155703701200000001
          aws-region: ap-southeast-1
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.5
          terraform_wrapper: false
      - run: |
          terraform init
          terraform apply -auto-approve
